name: Deploy flash-card-be to AWS docker

on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: .ansible/main.yml
          # Optional, SSH private key
          key: ${{secrets.AWS_SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{secrets.AWS}} address=localhost
          options: 
            -e GITHUB_REPO=${{github.repository}}
            -e NODE_ENV=${{vars.NODE_ENV}} 
            -e APP_PORT=${{vars.APP_PORT}}   
            -e APP_PATH=${{vars.APP_PATH}}
           